newsfeed/urls.py
from django.contrib import admin
from django.conf.urls import url

from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include, re_path

from user.tasks import feed_database
from .views import *
from user import api


urlpatterns = [
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path("user/", include("user.urls", namespace="users")),

    path('', index, name='index'),
    path('thanks/', LogoutPage.as_view(), name='thanks'),

    # rest framework endpoints
    path('api/auth/', include('rest_auth.urls')),

    re_path(r"^.*$", ErrorTemplateView.as_view(), name='entry-point'),

]

feed_database(repeat=10, repeat_until=None)

user/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'user'

from django.urls import path, include
from user.api.views import *

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"newsfeed", NewsFeedViewSet, basename='newsfeed')
router.register(r"userProfile", UserProfileViewSet, basename='userProfile')
router.register(r"user", UserViewSet, basename='user')

urlpatterns = [
    path('register',views.register, name='register'),
    url(r'user_login/$', views.user_login, name='login'),
    path('change/password/', views.change_password, name='change_password'),
    url(r'logout/$', views.user_logout, name='logout'),
    
    path('profile/', views.user_profile, name='profile'),
    path("everything", views.everyNewsTitle, name='everything'),
    path("set/settings", views.set_user_settings, name='user_settings'),
    path("filtered/newsfeed", views.get_filtered_response, name='filtered_newsfeed'),

    # rest urls
    path("api/", include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>PAS</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    <!-- Favicons -->
    <link href='{% static "assets/img/logo_small.jpg" %}' rel="icon">
    <!-- <link href='{% static "assets/img/apple-touch-icon.png" %}' rel="apple-touch-icon"> -->

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    <!-- Template Main CSS File -->
    <link href='{% static "assets/css/style.css" %}' rel="stylesheet">
    <!--  <link href='{% static "css/main.css" %}' rel="stylesheet">-->

    <!--  contains multiple select picker-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>


    <!--  export excel file-->
    <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>

</head>

<style>
    .bootstrap-select {
        width: 600px !important;
    }

    .navbar .nav-item .dropdown-menu {
        display: none;
    }

    .navbar .nav-item:hover .nav-link {
        color: #fff;
    }

    .navbar .nav-item:hover .dropdown-menu {
        display: block;
    }

    .navbar .nav-item .dropdown-menu {
        margin-top: 0;
    }


    body {
        font-family: Merriweather, Georgia, "times new roman", serif;
        color: #222;
    }


    font {
        font-style: normal;
        font-variant-ligatures: normal;
        font-variant-caps: normal;
        font-variant-numeric: normal;
        font-variant-east-asian: normal;
        font-weight: 400;
        font-stretch: normal;
        font-size: 18px;
        line-height: 1.8;
        font-family: Merriweather, Georgia, "times new roman", serif;
    }

    p {
        display: block;
        margin-block-start: 1em;
        margin-block-end: 1em;
        margin-inline-start: 0px;
        margin-inline-end: 0px;
        text-align: justify;
        margin-top: 0px;
        margin-bottom: 1rem;
    }


    a {
        color: #1bac91;
    }

    a:hover {
        color: #22d8b6;
        text-decoration: none;
    }

    h1, h2, h3, h4, h5, h6 {
        font-family: Merriweather, Georgia, "times new roman", serif;
    }


</style>

<body>
<!-- ======= Header ======= -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid">
        <div class="row container">
            <div class="col-md-2">
                <div class="navbar-header">
                    <a style="font-size:25px;" class="navbar-brand" href='{% url "index" %}'>NewsFeed</a>
                </div>

            </div>


            <div class="col-md-1"></div>

            <div class="col-md-9" style="float:right;">
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class=" navbar-nav dropdown">
                        <li class="nav-item active ">
                            <a class="nav-link" href='{% url "index" %}'>Home</a>
                        </li>


                        <li class="nav-item ">
                            <a class="nav-link" href='{% url "user:register" %}'>Register</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" href='{% url "user:everything" %}'>All Top Headlines</a>
                        </li>

                        {% if user.is_authenticated %}

                            {% if user.is_superuser %}
                                <li class="nav-item dropdown dropdown2">
                                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Status: Superuser
                                    </a>
                                    <div class="dropdown-menu dropdown-content"
                                         aria-labelledby="navbarDropdownMenuLink">

                                        <a class="dropdown-item" href="/admin/">Admin</a>
                                        <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                                    </div>
                                </li>

                            {% else %}

                                {% if current_user.chosen %}
                                    {% comment %}<li class="nav-item ">
                                        <a class="nav-link "
                                           style="cursor: not-allowed; pointer-events: all !important;"
                                           href="javascript:void(0)"
                                           title="Can't set filter more than once"
                                           style=""
                                        >Setup Settings</a>
                                    </li>{% endcomment %}
                                    <li class="nav-item ">
                                        <a class="nav-link" href='{% url "user:user_settings" %}'>Setup Settings</a>
                                    </li>

                                    <li class="nav-item ">
                                        <a class="nav-link" href='{% url "user:filtered_newsfeed" %}'>Filtered
                                            Newsfeed</a>
                                    </li>

                                {% else %}
                                    <li class="nav-item ">
                                        <a class="nav-link" href='{% url "user:user_settings" %}'>Setup Settings</a>
                                    </li>
                                {% endif %}

                                <li class="nav-item dropdown dropdown2">
                                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Status: User
                                    </a>
                                    <div class="dropdown-menu dropdown-content"
                                         aria-labelledby="navbarDropdownMenuLink">

                                        <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                                        <a class="dropdown-item" href="{% url 'user:change_password' %}">Change
                                            password</a>
                                        <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
                                    </div>
                                </li>
                            {% endif %}
                        {% else %}

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                            </li>

                        {% endif %}

                    </ul>
                </div>

            </div>

            <div class="col-md-0" style="width:80px;
                                    height:80px;
                                    top:10px;
                                    right:10px;
                                    z-index: 3;
                                    position:absolute;">
                <!-- Toggler/collapsibe Button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

        </div>
    </div>
</nav>

<div style="padding-top:100px;">
    {% block body_block %}

    {% endblock %}
</div>
<br>

<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">

            <div class="footer-info" style="text-align:center;">
                <h3> &#169; PAS -
                    <span>
                University Project allocation system <br>
              </span>
                </h3>
            </div>

        </div>
    </div>

</footer><!-- End Footer -->


</body>


</html>

templates/error.html
{% extends "base.html" %}
{% block body_block %}
<br><br>
<section id="steps" class="steps section-bg">
  <br><br>

  <div class="container jombotron">

    <h1 id="notfound">Sorry</h1>
    <h3 id="notfound"> 404 - Page Not Found! </h3>
    <br><br>

  </div>
<br><br>

</section>
<br><br>


<style>

#notfound{
  color: red;
  text-align: center;
}
</style>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
  <div class="container text-center text-md-left" data-aos="fade-up">
    <h1>Welcome to NewsFeed</h1>
    <h2 style="text-align:justify;"> </h2>

  </div>
</section><!-- End Hero -->

<main id="main">

</main>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block body_block %}

<div class="container jumbotron">
  <br>
  <h1>Thanks for visiting! Come back soon!</h1><br><br><br><br>
</div>

{% endblock %}